### ISSUE TITLE
Moodle System rejected the Request due to an Invalid parameter value

### ISSUE THREAD

**Issue by dazu89** [C0D3D3V/Moodle-DL#189]
## Description of the bug

Moodle-dl throws an error saying that the Moodle System rejected the Request due to an Invalid parameter value. The error started to occur suddenly, an update to the most recent version did not solve the problem. I would value any hint on how to track down the root of the issue.
 
## Error Message

```
04:00:10 Downloading account information
04:00:15 Loaded all lessons
04:00:15 Loaded all databases
04:00:15 Loaded all workshops
04:00:15 Loaded all folders
04:00:15 Loaded all pages
The following error occurred during execution:
The Moodle System rejected the Request. Details: invalid_parameter_exception (Errorcode: invalidparameter, Message: Invalid parameter value detected)
04:00:15 Exception: The Moodle System rejected the Request. Details: invalid_parameter_exception (Errorcode: invalidparameter, Message: Invalid parameter value detected)
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C82090FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C82090FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C82090FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C82090FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C82090FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C82090FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

## Technical details
 - OS: Windows
 - Python  3.9.16
 - Moodle-dl 2.3.1.5

**Comment by C0D3D3V** [comment]
😅 This error message is so useless xD I probably have to make that more verbose so that we gat more information on API errors.

Is this log created with the --verbose option?

Have you tried to remove your userid and moodle version from the log?

**Comment by C0D3D3V** [comment]
Please update moodle-dl and send again a log created with the  --verbose option

**Comment by dazu89** [comment]
Right, sorry for not doing so in the first place. The update did not resolve the issue, however, deactivating the download of submissions solved it for me - apparently none of the courses I am attending uses this feature. 
The user id is no longer saved into the config.json file.
```
(moodle-dl) D:\Users\User\Moodle>moodle-dl --verbose
2023-03-29 17:50:10  DEBUG  {main}  moodle-dl version: 2.3.1.6
2023-03-29 17:50:10  DEBUG  {main}  python version: 3.9.16
2023-03-29 17:50:10  DEBUG  {main}  Is ffmpeg available: True
2023-03-29 17:50:10  DEBUG  {main}  Checking for changes for the configured Moodle-Account....
2023-03-29 17:50:10  DEBUG  {database}  Database Version: 5
2023-03-29 17:50:10  DEBUG  {proactor_events}  Using proactor: IocpProactor
2023-03-29 17:50:10  DEBUG  {moodle_service}  Fetching current Moodle state...
2023-03-29 17:50:10  INFO  {moodle_service}  Downloading account information
2023-03-29 17:50:11  DEBUG  {connectionpool}  Starting new HTTPS connection (1): moodle-app2.let.ethz.ch:443
2023-03-29 17:50:12  DEBUG  {connectionpool}  https://moodle-app2.let.ethz.ch:443 "POST /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_webservice_get_site_info HTTP/1.1" 200 None
2023-03-29 17:50:12  DEBUG  {moodle_service}  Detected moodle version: 2021051713
2023-03-29 17:50:12  DEBUG  {cookie_handler}  Testing cookies using this URL: https://moodle-app2.let.ethz.ch/
2023-03-29 17:50:12  DEBUG  {connectionpool}  Starting new HTTPS connection (1): moodle-app2.let.ethz.ch:443
2023-03-29 17:50:13  DEBUG  {connectionpool}  https://moodle-app2.let.ethz.ch:443 "GET / HTTP/1.1" 200 None
2023-03-29 17:50:13  DEBUG  {cookie_handler}  Cookies are still valid
2023-03-29 17:50:13  DEBUG  {connectionpool}  Starting new HTTPS connection (1): moodle-app2.let.ethz.ch:443
2023-03-29 17:50:15  DEBUG  {connectionpool}  https://moodle-app2.let.ethz.ch:443 "POST /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_enrol_get_users_courses HTTP/1.1" 200 None
2023-03-29 17:50:15  INFO  {common}  Loaded all databases
2023-03-29 17:50:15  INFO  {common}  Loaded all lessons
2023-03-29 17:50:15  INFO  {common}  Loaded all workshops
2023-03-29 17:50:15  INFO  {common}  Loaded all folders
2023-03-29 17:50:15  INFO  {common}  Loaded all pages
2023-03-29 17:50:15  DEBUG  {request_helper}  Details about the failed request:
URL: https://moodle-app2.let.ethz.ch/webservice/rest/server.php?moodlewsrestformat=json&wsfunction=mod_assign_get_submissions
Body: {'assignmentids': {}}
The following error occurred during execution:
The Moodle System rejected the Request. Details: invalid_parameter_exception (Errorcode: invalidparameter, Message: Invalid parameter value detected)
2023-03-29 17:50:15  DEBUG  {mail_service}  Mail-Notifications not configured, skipping.
2023-03-29 17:50:15  DEBUG  {telegram_service}  Telegram-Notifications not configured, skipping.
2023-03-29 17:50:15  DEBUG  {xmpp_service}  XMPP-Notifications not configured, skipping.
2023-03-29 17:50:16  ERROR  {main}  Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\main.py", line 536, in main
    choose_task(config, opts)
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\main.py", line 68, in choose_task
    run_main(config, opts)
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\main.py", line 136, in run_main
    raise base_err
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\main.py", line 95, in run_main
    changed_courses = asyncio.run(moodle.fetch_state(database))
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\moodle_service.py", line 116, in fetch_state
    fetched_mods_files = await fetch_mods_files(mods, courses)
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\mods\__init__.py", line 40, in fetch_mods_files
    mods_results = await asyncio.gather(*[mod.fetch_mod_entries(courses_to_load) for mod in mods_to_fetch])
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\mods\common.py", line 57, in fetch_mod_entries
    result = await self.real_fetch_mod_entries(courses)
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\mods\assign.py", line 32, in real_fetch_mod_entries
    await self.add_foreign_submissions(result)
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\mods\assign.py", line 88, in add_foreign_submissions
    await self.client.async_post(
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\request_helper.py", line 140, in async_post
    self.check_json_for_moodle_error(resp_json, url, data)
  File "C:\mambaforge\current\envs\moodle-dl\lib\site-packages\moodle_dl\moodle\request_helper.py", line 318, in check_json_for_moodle_error
    raise RequestRejectedError(
moodle_dl.moodle.request_helper.RequestRejectedError: The Moodle System rejected the Request. Details: invalid_parameter_exception (Errorcode: invalidparameter, Message: Invalid parameter value detected)

2023-03-29 17:50:16  DEBUG  {main}  Exception-Handling completed. Exiting...
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001BA6242FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001BA6242FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001BA6242FD30>
Traceback (most recent call last):
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\mambaforge\current\envs\moodle-dl\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by C0D3D3V** [comment]
Ah nice that helped a lot :D I will make a fix

**Comment by C0D3D3V** [comment]
Please update again, and test with download submissions activated if the error still happens

**Comment by C0D3D3V** [comment]
Mh somehow v2.3.1.7 is not yet released... somhow the github CI does not run. so please wait till its released xD

**Comment by C0D3D3V** [comment]
https://www.githubstatus.com/ I guess that will take some more hours. I will ping here again as soon as the CI has run.

**Comment by C0D3D3V** [comment]
Now it should be released

**Comment by C0D3D3V** [comment]
Please open a new issue if the error happens again.
