### ISSUE TITLE
Crash when downloading course information

### ISSUE THREAD

**Issue by mr-brune** [C0D3D3V/Moodle-DL#192]
## Description of the bug
Program crash at the end of getting all the link to downlaod of a specific couse the other course dont have this problem

```
Downloading course information   1/  4 [INQ1097771 - DA..|  5246]

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/main.py", line 268, in run_main
    changed_courses = moodle.fetch_state()
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/moodle_connector/moodle_service.py", line 388, in fetch_state
    course.files = results_handler.fetch_files(course)
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/moodle_connector/results_handler.py", line 555, in fetch_files
    files = self._get_files_in_sections(course_sections)
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/moodle_connector/results_handler.py", line 66, in _get_files_in_sections
    files += self._get_files_in_modules(section_name, section_id, section_modules)
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/moodle_connector/results_handler.py", line 142, in _get_files_in_modules
    files += self._handle_files(
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/moodle_connector/results_handler.py", line 429, in _handle_files
    new_file = File(
  File "/usr/local/lib/python3.9/dist-packages/moodle_dl/state_recorder/file.py", line 41, in __init__
    self.content_timemodified = int(content_timemodified)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

The following error occurred during execution:
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
 

## Technical details

 - OS: Linux
 - Moodle-DL Version last

**Comment by C0D3D3V** [comment]
Thanks for the report. I will fix it tonight.
