### ISSUE TITLE
Moodle rejected system request - invalid_response_exception

### ISSUE THREAD

**Issue by davepivonka** [C0D3D3V/Moodle-DL#195]
## Explanation
Hello, I have been trying to get the downloader to work for the past hour, but despite trying to change different settings (e.g. disabling or enabling the cookie files or ignoring ytdl errors) and tried both normal and SSO logins, I have not been able to get it to work and the error is always the same. Is there anything I can do about this? :)

## Output without verbose
```
2023-06-29 18:45:04  DEBUG  {main}  Exception-Handling completed. Exiting...2023-06-29 19:03:39  INFO  {moodle_service}  Downloading account information
2023-06-29 19:03:40  INFO  {common}  Loaded all workshops
2023-06-29 19:03:40  INFO  {common}  Loaded all assignments
2023-06-29 19:03:41  INFO  {common}  Loaded all databases
2023-06-29 19:03:41  INFO  {common}  Loaded all quizzes
2023-06-29 19:03:41  INFO  {common}  Loaded all folders
2023-06-29 19:03:41  ERROR  {main}  Exception: The Moodle System rejected the Request. Details: invalid_response_exception (Error code: invalidresponse, Message: Invalid response value detected)
```

## Verbose output:
```
2023-06-29 18:47:18  DEBUG  {main}  moodle-dl version: 2.3.2.0
2023-06-29 18:47:18  DEBUG  {main}  python version: 3.11.2
2023-06-29 18:47:18  DEBUG  {main}  Is ffmpeg available: True
2023-06-29 18:47:18  DEBUG  {main}  Checking for changes for the configured Moodle-Account....
2023-06-29 18:47:18  DEBUG  {database}  Database Version: 5
2023-06-29 18:47:18  DEBUG  {selector_events}  Using selector: KqueueSelector
2023-06-29 18:47:18  DEBUG  {moodle_service}  Fetching current Moodle state...
2023-06-29 18:47:18  INFO  {moodle_service}  Downloading account information
2023-06-29 18:47:19  DEBUG  {connectionpool}  Starting new HTTPS connection (1): moodle.essex.ac.uk:443
2023-06-29 18:47:19  DEBUG  {connectionpool}  https://moodle.essex.ac.uk:443 "POST /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_webservice_get_site_info HTTP/1.1" 200 None
2023-06-29 18:47:19  DEBUG  {moodle_service}  Detected moodle version: 2022041905
2023-06-29 18:47:19  DEBUG  {connectionpool}  Starting new HTTPS connection (1): moodle.essex.ac.uk:443
2023-06-29 18:47:20  DEBUG  {connectionpool}  https://moodle.essex.ac.uk:443 "POST /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_enrol_get_users_courses HTTP/1.1" 200 None
2023-06-29 18:47:20  INFO  {common}  Loaded all workshops
2023-06-29 18:47:20  INFO  {common}  Loaded all databases
2023-06-29 18:47:20  INFO  {common}  Loaded all assignments
2023-06-29 18:47:20  INFO  {common}  Loaded all folders
2023-06-29 18:47:20  INFO  {common}  Loaded all quizzes
2023-06-29 18:47:20  INFO  {common}  Loaded all forums
2023-06-29 18:47:20  INFO  {common}  Loaded all pages
2023-06-29 18:47:21  DEBUG  {request_helper}  Details about the failed request:
URL: https://moodle.essex.ac.uk/webservice/rest/server.php?moodlewsrestformat=json&wsfunction=mod_lesson_get_lessons_by_courses
Body: {'moodlewssettingfilter': 'true', 'moodlewssettingfileurl': 'true', 'courseids': {'0': 5844, '1': 7106, '2': 16435, '3': 14431, '4': 3886, '5': 6373, '6': 16888, '7': 5838, '8': 6260, '9': 5034, '10': 2454, '11': 3201, '12': 4554, '13': 2334, '14': 3908, '15': 14695, '16': 1847, '17': 13058, '18': 14491, '19': 5368}, 'wsfunction': 'mod_lesson_get_lessons_by_courses', 'wstoken': 'censored'}
2023-06-29 18:47:21  DEBUG  {mail_service}  Mail-Notifications not configured, skipping.
2023-06-29 18:47:21  DEBUG  {telegram_service}  Telegram-Notifications not configured, skipping.
2023-06-29 18:47:21  DEBUG  {xmpp_service}  XMPP-Notifications not configured, skipping.
2023-06-29 18:47:21  ERROR  {main}  Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/main.py", line 536, in main
    choose_task(config, opts)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/main.py", line 68, in choose_task
    run_main(config, opts)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/main.py", line 136, in run_main
    raise base_err
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/main.py", line 95, in run_main
    changed_courses = asyncio.run(moodle.fetch_state(database))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/moodle/moodle_service.py", line 116, in fetch_state
    fetched_mods_files = await fetch_mods_files(mods, courses)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/moodle/mods/__init__.py", line 40, in fetch_mods_files
    mods_results = await asyncio.gather(*[mod.fetch_mod_entries(courses_to_load) for mod in mods_to_fetch])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/moodle/mods/common.py", line 57, in fetch_mod_entries
    result = await self.real_fetch_mod_entries(courses)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/moodle/mods/lesson.py", line 24, in real_fetch_mod_entries
    await self.client.async_post(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/moodle/request_helper.py", line 141, in async_post
    self.check_json_for_moodle_error(resp_json, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moodle_dl/moodle/request_helper.py", line 325, in check_json_for_moodle_error
    raise RequestRejectedError(
moodle_dl.moodle.request_helper.RequestRejectedError: The Moodle System rejected the Request. Details: invalid_response_exception (Error code: invalidresponse, Message: Invalid response value detected)

2023-06-29 18:47:21  DEBUG  {main}  Exception-Handling completed. Exiting...
```

**Comment by C0D3D3V** [comment]
@Aunib
That is a completly different issue. Please move it into an own issue.

**Comment by C0D3D3V** [comment]
Looks like a misconfiguration of your moodle instance, see https://moodle.org/mod/forum/discuss.php?d=343122 or https://moodle.org/mod/forum/discuss.php?d=355334

My guess is that for one of your lessones there is an error on the server. Currentlly moodle-dl has no option to deactivate loading of top level entries like lesson names. We should implement it.
