### ISSUE TITLE
Calendar mod fails with 'dict' object has no attribute 'append'

### ISSUE THREAD

**Issue by jopejoe1** [C0D3D3V/Moodle-DL#214]
## Steps to reproduce the issue

1. Enable Downloading of Calenders
2. Run moodle-dl

Note: this was a newly inited moodle-dl 

## Expected behavior
Not Crashing

## Possible Fix
Using list instead of dict (did not look deeply into it)

## Technical details

 - OS: Linux (NixOS)
 - Moodle-DL Version: 2.3.7

### Log
```log
The following error occurred during execution:
'dict' object has no attribute 'append'
2024-04-28 10:11:44  DEBUG  {mail_service}  Mail-Notifications not configured, skipping.
2024-04-28 10:11:44  DEBUG  {telegram_service}  Telegram-Notifications not configured, skipping.
2024-04-28 10:11:44  DEBUG  {xmpp_service}  XMPP-Notifications not configured, skipping.
2024-04-28 10:11:44  ERROR  {main}  Traceback (most recent call last):
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/main.py", line 547, in main
    choose_task(config, opts)
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/main.py", line 70, in choose_task
    run_main(config, opts)
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/main.py", line 138, in run_main
    raise base_err
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/main.py", line 97, in run_main
    changed_courses = asyncio.run(moodle.fetch_state(database))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/moodle/moodle_service.py", line 117, in fetch_state
    fetched_mods_files = await fetch_mods_files(mods, courses, core_contents)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/moodle/mods/__init__.py", line 44, in fetch_mods_files
    mods_results = await asyncio.gather(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/moodle/mods/common.py", line 59, in fetch_mod_entries
    result = await self.real_fetch_mod_entries(courses, core_contents)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/miydw2a6jk3cwqxv9yg3bqs4kdskpsp1-moodle-dl-2.3.7/lib/python3.11/site-packages/moodle_dl/moodle/mods/calendar.py", line 100, in real_fetch_mod_entries
    core_contents[course_id].append(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'

2024-04-28 10:11:44  DEBUG  {main}  Exception-Handling completed. Exiting...

```

**Comment by C0D3D3V** [comment]
Thank you very much for the report
